### PR TITLE
Fix tech metadata for non items

### LINKED ISSUE #320: Tech-metadata robot fails when called on non-object types
Tech-metadata generation depends on methods in the `Itemizable` concern, which is unavailable to other object types.

### PR DESCRIPTION
**Pull request by peetucket**
fixes #320 

also addresses another issue if an exception is raised in sdr-ingest

### CODE REVIEW

File: spec/models/concerns/preservable_spec.rb [hunk 1]
```diff
@@ -49,11 +49,18 @@ class PreservableItem < ActiveFedora::Base
 
   end
 
-  it 'builds the technicalMetadata datastream' do
+  it 'builds the technicalMetadata datastream if the object is an item' do
+    allow(item).to receive(:is_a?).and_return(Dor::Item)
```
Comment (jmartin-sul) [inline spec/models/concerns/preservable_spec.rb]: i think `is_a?` is supposed to return a boolean:
http://ruby-doc.org/core-2.4.1/Object.html#method-i-is_a-3F

Comment (peetucket) [inline spec/models/concerns/preservable_spec.rb]: good catch -- fixing both tests, rebasing and pushing in a minute
